vards = input('Programmu izstrādāja:')
print()
print('Laukuma aprēķins ģeometriskām figūrām')
print('    ****')
A = float(input('Ievadiet malas A garumu:'))
print(7)
print('Malas A garums:',(A))
print('    ****')
B = float(input('Ievadiet malas B garumu:'))
print(4)
print('Malas B garums:',(B))
print('    ****')
H = float(input('Ievadiet augstumu:'))
print(6)
print('Augstums:', (H))
print('Laukums trijstūrim:', A*H/2)
print('Laukums trapecei', (A+B)/2*H)
print('Laukums paralelogramam', (A*H))
print('    ****')
print('Paldies!')
