print('Divciparu skaitļa ciparu summas aprēķins')
print('Ievadiet divciparu skaitli!')
xy = int(input())
print('Divciparu skaitlis =', xy)
x = (xy//10)
y = (xy%10)
print('pirmais cipars:',x)
print('otrais cipars:',y)
print(x+y)